# Site settings
title: David Fu
email: davidf1212@gmail.com
description: Description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dvdfu
github_username:  dvdfu

# Build settings
markdown: kramdown
